// AUTO-GENERATED by demo/generate-db-schema.ts — do not edit manually.
// Run: npm run db:gen

export interface Database {
  departments: {
    id: number | null
    name: string | null
    budget: number | null
  }
  employee_skills: {
    id: number | null
    employee_id: number | null
    skill_id: number | null
    proficiency_level: number | null
    since_date: string | null
  }
  employee_teams: {
    id: number | null
    employee_id: number | null
    team_id: number | null
    role: string | null
    joined_at: string | null
  }
  employees: {
    id: number | null
    name: string | null
    email: string | null
    active: number | null
    sex: string | null
    nationality: string | null
    band: string | null
    birth_date: string | null
    start_date: string | null
    last_working_date: string | null
    manager_id: number | null
    department_id: number | null
    office_id: number | null
    salary: number | null
    city: string | null
    region: string | null
    country: string | null
    latitude: number | null
    longitude: number | null
    created_at: string | null
  }
  offices: {
    id: number | null
    name: string | null
    city: string | null
    region: string | null
    country: string | null
    latitude: number | null
    longitude: number | null
    created_at: string | null
  }
  performance_reviews: {
    id: number | null
    employee_id: number | null
    reviewer_id: number | null
    review_date: string | null
    period_start: string | null
    period_end: string | null
    rating: number | null
    created_at: string | null
  }
  pr_events: {
    id: number | null
    pr_number: number | null
    event_type: string | null
    employee_id: number | null
    timestamp: string | null
    created_at: string | null
  }
  productivity: {
    id: number | null
    employee_id: number | null
    department_id: number | null
    date: string | null
    lines_of_code: number | null
    pull_requests: number | null
    live_deployments: number | null
    days_off: number | null
    happiness_index: number | null
    created_at: string | null
  }
  skills: {
    id: number | null
    name: string | null
    category: string | null
    created_at: string | null
  }
  teams: {
    id: number | null
    name: string | null
    description: string | null
    department_id: number | null
    created_at: string | null
  }
}
