/**
 * Generates demo/db-schema.ts by introspecting the seeded SQLite database.
 *
 * Uses raw SQLite pragmas (not Kysely introspection) because the tables
 * live in an attached `analytics` schema that Kysely doesn't see by default.
 *
 * Usage: npm run db:gen
 */

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import Database from 'better-sqlite3'
import { seed } from './seeds.ts'

const __dirname = fileURLToPath(new URL('.', import.meta.url))

const sqliteDb = new Database(':memory:')
seed(sqliteDb)

const tables: Array<{ name: string; columns: Array<{ name: string; type: string; notnull: number }> }> = []

const rows = sqliteDb.prepare(
  "SELECT name FROM analytics.sqlite_master WHERE type='table' ORDER BY name"
).all() as Array<{ name: string }>

for (const { name } of rows) {
  const cols = sqliteDb.prepare(`PRAGMA analytics.table_info(${name})`).all() as Array<{
    name: string
    type: string
    notnull: number
  }>
  tables.push({ name, columns: cols })
}

const lines: string[] = [
  '// AUTO-GENERATED by demo/generate-db-schema.ts — do not edit manually.',
  '// Run: npm run db:gen',
  '',
  'export interface Database {',
]

for (const table of tables) {
  lines.push(`  ${table.name}: {`)
  for (const col of table.columns) {
    const tsType = sqlTypeToTs(col.type, col.notnull === 0)
    lines.push(`    ${col.name}: ${tsType}`)
  }
  lines.push('  }')
}

lines.push('}', '')
writeFileSync(join(__dirname, 'db-schema.ts'), lines.join('\n'))
console.log(`Generated demo/db-schema.ts (${tables.length} tables)`)

sqliteDb.close()

// ── Helpers ──────────────────────────────────────────────────────────────

function sqlTypeToTs(sqlType: string, nullable: boolean): string {
  const upper = sqlType.toUpperCase()
  let base: string

  if (upper.includes('INT')) {
    base = 'number'
  } else if (upper.includes('REAL') || upper.includes('FLOA') || upper.includes('DOUB')) {
    base = 'number'
  } else if (upper.includes('NUMERIC') || upper.includes('DECIMAL')) {
    base = 'number'
  } else {
    base = 'string'
  }

  return nullable ? `${base} | null` : base
}
